# Generated by Django 5.0.3 on 2024-03-22 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judges_review_api', '0003_alter_judgement_judge'),
    ]

    operations = [
        migrations.AddField(
            model_name='judgement',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
