# Generated by Django 4.2.11 on 2024-03-24 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judges_review_api', '0004_judgement_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='name',
        ),
    ]
